[package]
name = "chatui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
taffy = "0.9.1"
termwiz = "0.23.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[target.'cfg(unix)'.dependencies]
termios = "0.3"
