[package]
name = "term"
version = "0.1.0"
edition = "2024"

[dependencies]
chatui = { path = "../.." }
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
smol = "2"
taffy = "0.9.1"
tracing = "0.1"
