[package]
name = "dir_browser"
version = "0.1.0"
edition = "2024"

[dependencies]
chatui = { path = "../.." }
color-eyre = "0.6.5"
taffy = "0.9.1"
time = { version = "0.3", features = ["formatting"] }

[dev-dependencies]
tempfile = "3.10"
