[package]
name = "fuztea"
version = "0.1.0"
edition = "2024"

[dependencies]
chatui = { path = "../.." }
color-eyre = "0.6.5"
facet = "0.40.0"
facet-args = "0.40.0"
nucleo = "0.5.0"
parking_lot = "0.12"
smol = "2"
taffy = "0.9.1"
unicode-segmentation = "1.12"
unicode-width = "0.1.11"
